export const GET_LIST_PLAYERS = "GET_LIST_PLAYERS"
export const CREATE_NEW_PLAYER = "CREATE_NEW_PLAYER"
export const UPDATE_MODAL_PLAYER = "UPDATE_MODAL_PLAYER"
export const UPDATE_PLAYER = "UPDATE_PLAYER"